apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: demianight/anti_spam_back:latest
          ports:
            - containerPort: 8000
          env:
              - name : KAFKA_BROKER
                value: "kafka:9092"
              - name : DB_HOST
                value: "postgres"
              - name : DB_DB
                valueFrom: 
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_DB
              - name : DB_USER
                valueFrom: 
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_USER
              - name : DB_PASSWORD
                valueFrom: 
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
