[project]
name = "anti-spam-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.12",
    "psycopg[binary]>=3.2.9",
    "quixstreams>=3.16.0",
    "sqlmodel>=0.0.24",
]
